### ISSUE TITLE
error: duplicate octet on creating new scenario

### ISSUE THREAD

**Issue by exoriparian** [edurange/edurange3#18]
I believe this has something to do with the iteration strategy we discussed (and I thought fixed?) before

`[FLASK]   # docker_network.filly12345_PLAYER will be destroyed
[FLASK]   - resource "docker_network" "filly12345_PLAYER" {
[FLASK]       - attachable   = false -> null
[FLASK]       - driver       = "bridge" -> null
[FLASK]       - id           = "04db0854a6c71791ba8a518035e4ab68814a9daac57ef6f7449ed41122bae7f8" -> null
[FLASK]       - ingress      = false -> null
[FLASK]       - internal     = true -> null
[FLASK]       - ipam_driver  = "default" -> null
[FLASK]       - ipam_options = {} -> null
[FLASK]       - ipv6         = false -> null
[FLASK]       - name         = "filly12345_PLAYER" -> null
[FLASK]       - options      = {} -> null
[FLASK]       - scope        = "local" -> null
[FLASK] 
[FLASK]       - ipam_config {
[FLASK]           - aux_address = {} -> null
[FLASK]           - subnet      = "10.13.0.0/27" -> null
[FLASK]         }
[FLASK]     }
[FLASK] 
[FLASK] Plan: 0 to add, 0 to change, 2 to destroy.

[FLASK] Changes to Outputs:
[FLASK]   - filly12345_nat = [
[FLASK]       - {
[FLASK]           - ip_address_public = "er3.riparian.dev:HIDDEN"
[FLASK]           - name              = "filly12345_nat"
[FLASK]         },
[FLASK]     ] -> null
[FLASK] docker_network.filly12345_PLAYER: Destroying... [id=04db0854a6c71791ba8a518035e4ab68814a9daac57ef6f7449ed41122bae7f8]
[FLASK] docker_network.filly12345_NAT: Destroying... [id=4ba7be65980a65c776d5348c40ad4d22f3e313e52e6f6a0e460156f5d0388193]
[FLASK] docker_network.filly12345_NAT: Destruction complete after 2s
[FLASK] docker_network.filly12345_PLAYER: Destruction complete after 2s
[FLASK] 
[FLASK] Destroy complete! Resources: 2 destroyed.
127.0.0.1 - - [08/Apr/2024 02:47:20] "POST /api/scenario_interface HTTP/1.1" 200 -
[FLASK] 127.0.0.1 - - [08/Apr/2024 02:47:22] "POST /api/scenario_interface HTTP/1.1" 200 -
[CELERY] 
[CELERY] Initializing the backend...
[CELERY] 
[CELERY] Initializing provider plugins...
[CELERY] - Finding latest version of kreuzwerker/docker...
[CELERY] - Installing kreuzwerker/docker v3.0.2...
[CELERY] - Installed kreuzwerker/docker v3.0.2 (self-signed, key ID BD080C4571C6104C)
[CELERY] 
[CELERY] Partner and community providers are signed by their developers.
[CELERY] If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
[CELERY] 
[CELERY] Terraform has created a lock file .terraform.lock.hcl to record the provider
[CELERY] selections it made above. Include this file in your version control repository
[CELERY] so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
[CELERY] 
[CELERY] Terraform has been successfully initialized!
[CELERY] 
[CELERY] You may now begin working with Terraform. Try running "terraform plan" to see
[CELERY] any changes that are required for your infrastructure. All Terraform commands
[CELERY] should now work.
[CELERY] 
[CELERY] If you ever set or change modules or backend configuration for Terraform,
[CELERY] rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[CELERY] 
[CELERY] Terraform used the selected providers to generate the following execution
[CELERY] plan. Resource actions are indicated with the following symbols:
[CELERY]   + create

[CELERY] Terraform will perform the following actions:
[CELERY] 
[CELERY]   # docker_network.filbro1_NAT will be created
[CELERY]   + resource "docker_network" "filbro1_NAT" {
[CELERY]       + driver      = "bridge"
[CELERY]       + id          = (known after apply)
[CELERY]       + internal    = false
[CELERY]       + ipam_driver = "default"
[CELERY]       + name        = "filbro1_NAT"
[CELERY]       + options     = (known after apply)
[CELERY]       + scope       = (known after apply)
[CELERY] 
[CELERY]       + ipam_config {
[CELERY]           + subnet = "10.14.1.0/27"
[CELERY]         }
[CELERY]     }
[CELERY] 
[CELERY]   # docker_network.filbro1_PLAYER will be created
[CELERY]   + resource "docker_network" "filbro1_PLAYER" {
[CELERY]       + driver      = "bridge"
[CELERY]       + id          = (known after apply)
[CELERY]       + internal    = true
[CELERY]       + ipam_driver = "default"
[CELERY]       + name        = "filbro1_PLAYER"
[CELERY]       + options     = (known after apply)
[CELERY]       + scope       = (known after apply)
[CELERY] 
[CELERY]       + ipam_config {
[CELERY]           + subnet = "10.14.0.0/27"
[CELERY]         }
[CELERY]     }
[CELERY] 
[CELERY] Plan: 2 to add, 0 to change, 0 to destroy.

[CELERY] ─────────────────────────────────────────────────────────────────────────────
[CELERY] 
[CELERY] Saved the plan to: network
[CELERY] 
[CELERY] To perform exactly these actions, run the following command to apply:
[CELERY]     terraform apply "network"
[FLASK] [2024-04-08 02:47:41,908] ERROR in app: Exception on /api/scenario_interface [POST]
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
[FLASK]     response = self.full_dispatch_request()
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
[FLASK]     rv = self.handle_user_exception(e)
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
[FLASK]     rv = self.dispatch_request()
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
[FLASK]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[FLASK]   File "/home/riparian/edurange3/py_flask/utils/auth_utils.py", line 48, in wrapper
[FLASK]     return fn(*args, **kwargs)
[FLASK]   File "/home/riparian/edurange3/py_flask/routes/instructor_routes.py", line 307, in scenario_interface
[FLASK]     returnJSON = methodToUse(requestJSON)
[FLASK]   File "/home/riparian/edurange3/py_flask/routes/instructor_routes.py", line 239, in create_scenario
[FLASK]     returnObj = create_scenario_task.delay(scenario_name, scenario_type, students_list, group_id, scenario_id).get(timeout=None)
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/celery/result.py", line 251, in get
[FLASK]     return self.backend.wait_for_pending(
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/celery/backends/asynchronous.py", line 223, in wait_for_pending
[FLASK]     return result.maybe_throw(callback=callback, propagate=propagate)
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/celery/result.py", line 365, in maybe_throw
[FLASK]     self.throw(value, self._to_remote_traceback(tb))
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/celery/result.py", line 358, in throw
[FLASK]     self.on_ready.throw(*args, **kwargs)
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/vine/promises.py", line 235, in throw
[FLASK]     reraise(type(exc), exc, tb)
[FLASK]   File "/home/riparian/.local/lib/python3.10/site-packages/vine/utils.py", line 27, in reraise
[FLASK]     raise value
[FLASK] Exception: <class 'sqlalchemy.exc.IntegrityError'>(['(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "scenarios_octet_key"\nDETAIL:  Key (octet)=(14) already exists.\n'])
[FLASK] 127.0.0.1 - - [08/Apr/2024 02:47:41] "POST /api/scenario_interface HTTP/1.1" 500 -`

**Comment by exoriparian** [comment]
i'm working on a strategy to add/remove the used octets in a csv on build/destroy

**Comment by exoriparian** [comment]
I believe I've fixed it. I made 2 functions to add/discard ints into a csv which acts as an octet set.  the new functions are 'claimOctet()' and 'discardOctet()' in py_flask/utils/csv_utils.py
