### ISSUE TITLE
install script needs new variable names for NODE values

### ISSUE THREAD

**Issue by exoriparian** [edurange/edurange3#39]
currently you will get an error like this: 
```
[NODE] /home/riparian/edurange4/edurange3/node/node_modules/pg-pool/index.js:45
[NODE]     Error.captureStackTrace(err)
[NODE]           ^
[NODE] 
[NODE] Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
[NODE]     at /home/riparian/edurange4/edurange3/node/node_modules/pg-pool/index.js:45:11
[NODE]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[NODE]     at async handleConnection (/home/riparian/edurange4/edurange3/node/er3_modules/er3_chat.js:259:22)
[NODE]     at async WebSocketServer.<anonymous> (/home/riparian/edurange4/edurange3/node/er3_modules/er3_chat.js:289:5)
[NODE] 
[NODE] Node.js v21.7.3
```

That is because it is looking for these variables in the main .env, but
they are missing because the ./install.sh doesn't set them correctly

CHATDB_USERNAME,
CHATDB_LOCALHOST,
CHATDB_DATABASENAME,
CHATDB_PASSWORD,
CHATDB_PORT

solution:  
add these to install script
OR
leave out LOCALHOST and PORT and use 127.0.0.1 and 5432 by default in er3_chat.js

might be better to set explicitly though

**Comment by exoriparian** [comment]
fixed with updates to env.example
